version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
    env_file:
      - gateway.env
    ports:
      - 8000:8000
  trips:
    build:
      context: ./trips
    env_file:
      - trips.env
  airports:
    build:
      context: ./airports
    env_file:
      - airports.env
  redis-trips:
    image: redis:7-alpine
  redis-airport:
    image: redis:7-alpine
  mq:
    image: rabbitmq:3-management
