version: "3.8"

services:
  gateway:
    build:
      context: ./gateway
    env_file:
      - gateway.env
    ports:
      - 8000:8000
  trips:
    build:
      context: ./trips
    env_file:
      - trips.env
  mq:
    image: rabbitmq:3-management
